server:
  port: 8010

spring:
  application:
    name: cloud-case-gateway
  profiles:
    active: prod
# 路由断言 配置文件格式 还可以使用编码式，两者二选一
#  cloud:
#    gateway:
#      routes:
#        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
#          #匹配后提供服务的路由地址
#          uri: http://localhost:8096 # 可是要服务名
#          predicates:
#            - Path=/payment/hystrix/** # 断言，路径相匹配的进行路由 根据路由正则匹配
#        - id: payment_route2
#          uri: http://localhost:8092
#          predicates:
#            Path=/payment/get/** #断言,路径相匹配的进行路由

#注册中心，eureka
eureka:
  client:
    #表示是否将自己注册进eureka  默认为true
    register-with-eureka: true
    #是否从EurekaServer中抓取已有的注册信息，默认为true，单点无所谓，集群必须设置true才能和ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #集群配置
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    #服务名称修改
    instance-id: cloudCaseGateway${server.port}
    #访问路径可以显示ip地址
    prefer-ip-address: true

logging:
  file:
    path: D:/elasticsearch/logs
  config: classpath:logback-spring.xml