server:
  port: 8060
spring:
  application:
    name: cloud-case-consumer-openFeign
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      #集群配置
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    #服务名称修改
    instance-id: consumerOpenFeign${server.port}
    #访问路径可以显示ip地址
    prefer-ip-address: true

# 设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  # 指的是建立连接所用的时间,适用于网络状态正常的情况下,两端连接所用的时间，设置等待5000为5秒时间
  ReadTimeout: 5000
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000
logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.zy.cloud.openFeign.service.PaymentFeginService: info