# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8021

# RabbitMQ相关配置 springcloud bus
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  profiles:
    active: prod
logging:
  file:
    path: D:/elasticsearch/logs
  config: classpath:logback-spring.xml